### ISSUE TITLE
Not blocked websockets with non-standard port

### ISSUE THREAD

**Issue by FTOH** [gorhill/uBO-WebSocket#10]
Google Chrome 52.0.2743.116 m (64-bit)
uBlock Origin v1.9.6, uBlock Origin WebSocket v1.1

https://nnmclub.to/

![image](https://cloud.githubusercontent.com/assets/5018813/18416210/a344788a-7837-11e6-8fa7-0054fc3496f2.png)

**Comment by gorhill** [comment]
Duplicate of #8.
