### ISSUE TITLE
Merge with uBO

### ISSUE THREAD

**Issue by migueldemoura** [gorhill/uBO-WebSocket#11]
Why is this a separate extension and not integrated into the main one?
Compatibility? Permissions?

Isn't it possible to implement this functionality and keep it optional (not adding the wrapper)?

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/issues/1801

**Comment by migueldemoura** [comment]
I only searched the issues in this repo, not the other one. Thanks!
