### ISSUE TITLE
Domains using WebSocket for ads

### ISSUE THREAD

**Issue by MarkTheLover** [gorhill/uBO-WebSocket#2]
Since I can't create a new pull request, I'm posting this list as an issue.
 
NSFW - pornhub.com - ws - abbp1.pw
postimg.org - ws - mgid.com

More will be added as I come across...

**Comment by gorhill** [comment]
For filter issues, it is uAssets. Here is for code issue.

**Comment by gorhill** [comment]
also, `mgid.com` is already in Peter Lowe's, it should be filtered by default.

**Comment by gorhill** [comment]
I will add `abbp1.pw` to uBO's filters however.

**Comment by IDKwhattoputhere** [comment]
https://github.com/easylist/easylist/commit/61dfc7d8be32a7cb17c9ff75d3849f3c6ce77557

**Comment by MarkTheLover** [comment]
By issue I meant in issue section and not exactly as an issue, and yes I know mgid is blocked, but I posting the list and I couldn't pull request so I posted here instead, oh well.

**Comment by IDKwhattoputhere** [comment]
What did you want to put into the pull request? There are no filters in this repo and they don't belong here, only the extension's code.

**Comment by MarkTheLover** [comment]
> What did you want to put into the pull request?

https://github.com/gorhill/uBO-WebSocket#sites-benefitting-from-websocket-filtering

Read that. I wanted to add these sites to that list, thats all.

**Comment by gorhill** [comment]
I see, sorry for the misunderstanding, I forgot about this.

**Comment by MarkTheLover** [comment]
Yeah well, shit happens I guess.

**Comment by IDKwhattoputhere** [comment]
Maybe name/link the file next time to avoid confusion.

**Comment by MarkTheLover** [comment]
Found another one on thevideo.me, shall I report on uAssets ?
