### ISSUE TITLE
No Firefox version available

### ISSUE THREAD

**Issue by davidhedlund** [gorhill/uBO-WebSocket#9]
I do not see uBlock Origin WebSocket on AMO. It would be useful.

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBO-WebSocket#purpose
> For **Chromium-based browsers**, WebSocket connections are not available to the chrome.webRequest API.

It's purpose is to fix an issue with Chromium . Firefox is **not** Chromium-based and last time I checked didn't have this issue. So how would it be useful?

**Comment by davidhedlund** [comment]
@IDKwhattoputhere Sorry. You are right, this work for Firefox by default. Nothing have to be added.
